account_id = "ACCT_ID"
compatibility_date = "2022-06-07"
kv_namespaces = [{binding = "KV", id = "KV_ID"}]
main = "dist/worker.production.js"
name = "uau-next-gen"
routes = [
  {pattern = "two.li", custom_domain = true},
]
type = "webpack"
webpack_config = "webpack.config.js"

[build]
command = "npm run build"

[placement]
mode = "smart"
