account_id = "ACCT_ID"
compatibility_date = "2024-11-16"
kv_namespaces = [{binding = "KV", id = "KV_ID"}]
main = "src/index.ts"
name = "uau-next-gen"
routes = [
  {pattern = "two.li", custom_domain = true},
]

[placement]
mode = "smart"
